// <auto-generated />
using System;
using DysonHarness;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Harness.Engine.Migrations
{
    [DbContext(typeof(DysonDbContext))]
    [Migration("20260723222659_AddModelFavorites")]
    partial class AddModelFavorites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DysonHarness.DysonModelFavoriteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelSlugId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelSlugId")
                        .IsUnique();

                    b.ToTable("model_favorites", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonModelProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("model_providers", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonModelSlugEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayAlias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("ProviderId", "Slug")
                        .IsUnique();

                    b.ToTable("model_slugs", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("McpAccessMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModelSlugId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuntimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPromptSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastActivityUtc");

                    b.HasIndex("ModelSlugId");

                    b.HasIndex("ParentSessionId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonSessionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TurnId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TurnId");

                    b.HasIndex("SessionId", "Kind");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("session_logs", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonTurnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantText")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompactToolHistory")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ToolHistoryOptimized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("turns", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonModelFavoriteEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonModelSlugEntity", "ModelSlug")
                        .WithMany()
                        .HasForeignKey("ModelSlugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelSlug");
                });

            modelBuilder.Entity("DysonHarness.DysonModelSlugEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonModelProviderEntity", "Provider")
                        .WithMany("Slugs")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("DysonHarness.DysonSessionEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonModelSlugEntity", "ModelSlug")
                        .WithMany()
                        .HasForeignKey("ModelSlugId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DysonHarness.DysonSessionEntity", "ParentSession")
                        .WithMany()
                        .HasForeignKey("ParentSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModelSlug");

                    b.Navigation("ParentSession");
                });

            modelBuilder.Entity("DysonHarness.DysonSessionLogEntry", b =>
                {
                    b.HasOne("DysonHarness.DysonSessionEntity", "Session")
                        .WithMany("Logs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DysonHarness.DysonTurnEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonSessionEntity", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DysonHarness.DysonModelProviderEntity", b =>
                {
                    b.Navigation("Slugs");
                });

            modelBuilder.Entity("DysonHarness.DysonSessionEntity", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
