// <auto-generated />
using System;
using DysonHarness;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Harness.LocalDb.Migrations
{
    [DbContext(typeof(DysonDbContext))]
    partial class DysonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DysonHarness.DysonAppSettingEntity", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId", "Key");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonConfiguredShellEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FixedArgsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId", "Name")
                        .IsUnique();

                    b.ToTable("configured_shells", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonModelFavoriteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelSlugId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelSlugId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId", "ModelSlugId")
                        .IsUnique();

                    b.ToTable("model_favorites", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonModelProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagedSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenAiApiMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId", "ManagedSource")
                        .IsUnique();

                    b.ToTable("model_providers", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonModelSlugEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultMaxTargetContextTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultReasoningEffort")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayAlias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningModes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("ProviderId", "Slug")
                        .IsUnique();

                    b.ToTable("model_slugs", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonPluginHookAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HookComponentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InputBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId", "InstallationId", "OccurredUtc");

                    b.ToTable("plugin_hook_audits", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonPluginHookReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HookComponentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxOutputBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageChecksum")
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReviewedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId", "InstallationId", "HookComponentId", "EventName")
                        .IsUnique();

                    b.ToTable("plugin_hook_reviews", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonPluginInstallationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentInventoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationSchemaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentChecksum")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallScope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstalledUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedPluginId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("PackageFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageRoot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedCommit")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSubdirectory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkDirectoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("WorkDirectoryId");

                    b.HasIndex("SubjectId", "NormalizedPluginId")
                        .IsUnique()
                        .HasFilter("\"InstallScope\" = 'Global'");

                    b.HasIndex("SubjectId", "PackageRoot")
                        .IsUnique();

                    b.HasIndex("SubjectId", "NormalizedPluginId", "WorkDirectoryId")
                        .IsUnique()
                        .HasFilter("\"InstallScope\" = 'Project'");

                    b.ToTable("plugin_installations", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonPluginMcpGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capabilities")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GrantedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageChecksum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId", "InstallationId", "ServerId")
                        .IsUnique();

                    b.ToTable("plugin_mcp_grants", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonPluginVariableValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId", "InstallationId", "VariableName")
                        .IsUnique();

                    b.ToTable("plugin_variable_values", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxTargetContextTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("McpAccessMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModelSlugId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningEffort")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuntimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPromptSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkDirectoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastActivityUtc");

                    b.HasIndex("ModelSlugId");

                    b.HasIndex("ParentSessionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("WorkDirectoryId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonSessionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TurnId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TurnId");

                    b.HasIndex("SessionId", "Kind");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("session_logs", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonSessionTodoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence");

                    b.HasIndex("SessionId", "TaskCode")
                        .IsUnique();

                    b.ToTable("session_todos", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonSubjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonTurnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantText")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompactToolHistory")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcludedFromContext")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningLogJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningText")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillsUsedJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ToolHistoryOptimized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserImagesJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("turns", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonWorkDirectoryConfigurationEntity", b =>
                {
                    b.Property<Guid>("WorkDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkDirectoryId");

                    b.HasIndex("SubjectId");

                    b.ToTable("work_directory_configurations", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonWorkDirectoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbsolutePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastOpenedUtc");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId", "AbsolutePath")
                        .IsUnique();

                    b.ToTable("work_directories", (string)null);
                });

            modelBuilder.Entity("DysonHarness.DysonModelFavoriteEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonModelSlugEntity", "ModelSlug")
                        .WithMany()
                        .HasForeignKey("ModelSlugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelSlug");
                });

            modelBuilder.Entity("DysonHarness.DysonModelSlugEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonModelProviderEntity", "Provider")
                        .WithMany("Slugs")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("DysonHarness.DysonPluginHookAuditEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonPluginInstallationEntity", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("DysonHarness.DysonPluginHookReviewEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonPluginInstallationEntity", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("DysonHarness.DysonPluginInstallationEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonWorkDirectoryEntity", "WorkDirectory")
                        .WithMany()
                        .HasForeignKey("WorkDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("WorkDirectory");
                });

            modelBuilder.Entity("DysonHarness.DysonPluginMcpGrantEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonPluginInstallationEntity", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("DysonHarness.DysonPluginVariableValueEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonPluginInstallationEntity", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("DysonHarness.DysonSessionEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonModelSlugEntity", "ModelSlug")
                        .WithMany()
                        .HasForeignKey("ModelSlugId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DysonHarness.DysonSessionEntity", "ParentSession")
                        .WithMany()
                        .HasForeignKey("ParentSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DysonHarness.DysonWorkDirectoryEntity", "WorkDirectory")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkDirectoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModelSlug");

                    b.Navigation("ParentSession");

                    b.Navigation("WorkDirectory");
                });

            modelBuilder.Entity("DysonHarness.DysonSessionLogEntry", b =>
                {
                    b.HasOne("DysonHarness.DysonSessionEntity", "Session")
                        .WithMany("Logs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DysonHarness.DysonSessionTodoEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonSessionEntity", "Session")
                        .WithMany("Todos")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DysonHarness.DysonTurnEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonSessionEntity", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DysonHarness.DysonWorkDirectoryConfigurationEntity", b =>
                {
                    b.HasOne("DysonHarness.DysonWorkDirectoryEntity", "WorkDirectory")
                        .WithOne()
                        .HasForeignKey("DysonHarness.DysonWorkDirectoryConfigurationEntity", "WorkDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkDirectory");
                });

            modelBuilder.Entity("DysonHarness.DysonModelProviderEntity", b =>
                {
                    b.Navigation("Slugs");
                });

            modelBuilder.Entity("DysonHarness.DysonSessionEntity", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Todos");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("DysonHarness.DysonWorkDirectoryEntity", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
