#!/usr/bin/env bash
# Resolves git branch → DysonAppMode and writes DysonBuildInfo.g.cs
set -euo pipefail

OUTPUT_PATH="${1:?OutputPath required}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
branch=""
mode="Dev"

if branch="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null)"; then
  branch="$(printf '%s' "$branch" | tr -d '\r\n')"
  if [[ -z "$branch" || "$branch" == "HEAD" ]]; then
    branch=""
    mode="Dev"
  else
    case "$(printf '%s' "$branch" | tr '[:upper:]' '[:lower:]')" in
      main|master) mode="Prod" ;;
      develop|test|testing) mode="Test" ;;
      *) mode="Dev" ;;
    esac
  fi
else
  branch=""
  mode="Dev"
fi

escaped_branch="${branch//\\/\\\\}"
escaped_branch="${escaped_branch//\"/\\\"}"

content="// <auto-generated />
#nullable enable
namespace DysonHarness;

public static class DysonBuildInfo
{
    public static DysonAppMode Current { get; } = DysonAppMode.${mode};
    public static string BranchName { get; } = \"${escaped_branch}\";
}
"

mkdir -p "$(dirname "$OUTPUT_PATH")"

if [[ -f "$OUTPUT_PATH" ]]; then
  existing="$(cat "$OUTPUT_PATH")"
  if [[ "$existing" == "$content" ]]; then
    exit 0
  fi
fi

printf '%s\n' "$content" > "$OUTPUT_PATH"
