# Resolves git branch → DysonAppMode and writes DysonBuildInfo.g.cs
# Priority: DYSON_APP_MODE → DYSON_BRANCH_NAME → GITHUB_REF_NAME (Actions branch) → git HEAD
param(
    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = "Continue"

function Get-ModeFromBranch([string]$BranchName) {
    switch ($BranchName.ToLowerInvariant()) {
        { $_ -in @("main", "master") } { return "Prod" }
        { $_ -in @("develop", "test", "testing") } { return "Test" }
        default { return "Dev" }
    }
}

function Get-NormalizedMode([string]$Raw) {
    switch ($Raw.ToLowerInvariant()) {
        "prod" { return "Prod" }
        "test" { return "Test" }
        "dev" { return "Dev" }
        default { return $null }
    }
}

$branch = ""
$mode = $null

$appModeOverride = [Environment]::GetEnvironmentVariable("DYSON_APP_MODE")
if (-not [string]::IsNullOrWhiteSpace($appModeOverride)) {
    $mode = Get-NormalizedMode $appModeOverride.Trim()
}

$branchOverride = [Environment]::GetEnvironmentVariable("DYSON_BRANCH_NAME")
if (-not [string]::IsNullOrWhiteSpace($branchOverride)) {
    $branch = $branchOverride.Trim()
}
elseif ([Environment]::GetEnvironmentVariable("GITHUB_ACTIONS") -eq "true") {
    $refName = [Environment]::GetEnvironmentVariable("GITHUB_REF_NAME")
    $refType = [Environment]::GetEnvironmentVariable("GITHUB_REF_TYPE")
    $ref = [Environment]::GetEnvironmentVariable("GITHUB_REF")
    if (-not [string]::IsNullOrWhiteSpace($refName) -and (
            $refType -eq "branch" -or
            ($ref -and $ref.StartsWith("refs/heads/")))) {
        $branch = $refName.Trim()
    }
}

if ([string]::IsNullOrWhiteSpace($branch)) {
    try {
        Push-Location (Split-Path -Parent $PSScriptRoot)
        $gitOut = & git rev-parse --abbrev-ref HEAD 2>$null
        if ($LASTEXITCODE -eq 0 -and $gitOut) {
            $branch = [string]$gitOut.Trim()
            if ([string]::IsNullOrWhiteSpace($branch) -or $branch -eq "HEAD") {
                $branch = ""
            }
        }
    }
    catch {
        $branch = ""
    }
    finally {
        Pop-Location -ErrorAction SilentlyContinue
    }
}

if ([string]::IsNullOrWhiteSpace($mode)) {
    if ([string]::IsNullOrWhiteSpace($branch)) {
        $mode = "Dev"
    }
    else {
        $mode = Get-ModeFromBranch $branch
    }
}

$escapedBranch = $branch.Replace("\", "\\").Replace("""", "\""")

$content = @"
// <auto-generated />
#nullable enable
namespace DysonHarness;

public static class DysonBuildInfo
{
    public static DysonAppMode Current { get; } = DysonAppMode.$mode;
    public static string BranchName { get; } = "$escapedBranch";
}
"@

$dir = Split-Path -Parent $OutputPath
if ([string]::IsNullOrWhiteSpace($dir)) {
    $dir = (Get-Location).Path
    $OutputPath = Join-Path $dir (Split-Path -Leaf $OutputPath)
}
if (-not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

# Avoid rewriting identical content (keeps incremental builds happy).
if (Test-Path -LiteralPath $OutputPath) {
    $existing = Get-Content -LiteralPath $OutputPath -Raw -ErrorAction SilentlyContinue
    if ($existing -eq $content) {
        exit 0
    }
}

[System.IO.File]::WriteAllText($OutputPath, $content)
