# Resolves git branch → DysonAppMode and writes DysonBuildInfo.g.cs
param(
    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = "Continue"

$branch = ""
$mode = "Dev"

try {
    Push-Location (Split-Path -Parent $PSScriptRoot)
    $gitOut = & git rev-parse --abbrev-ref HEAD 2>$null
    if ($LASTEXITCODE -eq 0 -and $gitOut) {
        $branch = [string]$gitOut.Trim()
        if ([string]::IsNullOrWhiteSpace($branch) -or $branch -eq "HEAD") {
            $branch = ""
            $mode = "Dev"
        }
        else {
            switch ($branch.ToLowerInvariant()) {
                { $_ -in @("main", "master") } { $mode = "Prod" }
                { $_ -in @("develop", "test", "testing") } { $mode = "Test" }
                default { $mode = "Dev" }
            }
        }
    }
}
catch {
    $branch = ""
    $mode = "Dev"
}
finally {
    Pop-Location -ErrorAction SilentlyContinue
}

$escapedBranch = $branch.Replace("\", "\\").Replace("""", "\""")

$content = @"
// <auto-generated />
#nullable enable
namespace DysonHarness;

public static class DysonBuildInfo
{
    public static DysonAppMode Current { get; } = DysonAppMode.$mode;
    public static string BranchName { get; } = "$escapedBranch";
}
"@

$dir = Split-Path -Parent $OutputPath
if ([string]::IsNullOrWhiteSpace($dir)) {
    $dir = (Get-Location).Path
    $OutputPath = Join-Path $dir (Split-Path -Leaf $OutputPath)
}
if (-not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

# Avoid rewriting identical content (keeps incremental builds happy).
if (Test-Path -LiteralPath $OutputPath) {
    $existing = Get-Content -LiteralPath $OutputPath -Raw -ErrorAction SilentlyContinue
    if ($existing -eq $content) {
        exit 0
    }
}

[System.IO.File]::WriteAllText($OutputPath, $content)
